#!/usr/bin/env bash

# correct commit spelling automatically

commit_msg=$1

words=$(grep -v "^#" $commit_msg | aspell list)

echo $words

echo $@

if [ ! "$words" ]; then
  exit 0
fi

printf "%s\n" "Following words flagged:
----------------------------------------"
echo $words

# find out if they want to abort
printf "abort commit to fix errors? [Y/N] "
while true; do
  exec < /dev/tty  # git hooks are detached from stdin
  read response
  shopt -s nocasematch
  case "$response" in
    y|yes)
      exit 1
      ;;
    n|no)
      exit 0
      ;;
    *)
      printf "huh? abort commit to fix errors? [Y/N] "
      continue
  esac
  shopt -u nocasematch
done
