#!/usr/bin/env bash

# correct commit spelling automatically

commit_msg=$1

filter() {
  echo $(python3 - << EOF

bld_str = []
with open("$1", 'r') as f:
  for l in f:
    if l.strip() == '# ------------------------ >8 ------------------------':
      break
    elif l[0] != '#' and l.strip() != '':
      bld_str.append(l.strip())
print(' '.join(bld_str))

EOF
  )
}

words=$(filter $commit_msg | aspell list)

if [ ! "$words" ]; then
  exit 0
fi

printf "%s\n" "Following words flagged:
----------------------------------------"
for w in $words; do
  echo $w
done

# find out if they want to abort
printf "abort commit to fix errors? [Y/N] "
while true; do
  exec < /dev/tty  # git hooks are detached from stdin
  read response
  shopt -s nocasematch
  case "$response" in
    y|yes)
      exit 1
      ;;
    n|no)
      exit 0
      ;;
    *)
      printf "huh? abort commit to fix errors? [Y/N] "
      continue
  esac
  shopt -u nocasematch
done
