#!/usr/bin/env bash

PREV_HEAD=$1
NEW_HEAD=$2
IS_BRANCH=$3

if [[ "$IS_BRANCH" -eq "1" && -z "$( git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)" )" ]]; then
  git push --set-upstream $( git remote show ) "$(git symbolic-ref -q HEAD)"
fi

exit 0
