#!/usr/bin/env bash

if [[ -z "$( git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)" )" ]]; then
  git push --set-upstream $( git remote show ) "$(git symbolic-ref -q HEAD)"
fi

exit 0
