#!/usr/bin/env bash

PREV_HEAD=$1
NEW_HEAD=$2
IS_BRANCH=$3

if [[ "$IS_BRANCH" -eq "1" ]]; then
  # create a remote, upstream branch if one doesn't exist
  if [[ -z "$( git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)" )" ]]; then
    git push --set-upstream $( git remote show ) "$(git symbolic-ref -q HEAD)"
  fi

  # run whatever clean script there is
  ./clean.sh

  # update repos we depend on, assumes update.sh in parent directory
  ../update.sh

  # do a full rebuild
  ./rebuild.sh
fi

exit 0
