#!/usr/bin/env bash

# first, we check if there are whitespace issues
if ! git diff-index --check --cached HEAD; then
    printf "\nThere are whitespace issues!\n"
    exit 1
fi

# next, we check if there are linting issues
result=0
for f in $( git diff-index --name-only --cached HEAD | grep '.*js$' ); do
  if ! ./node_modules/eslint/bin/eslint.js $f; then
    result=1
  fi
done
if [ "$result" -eq "1" ]; then
  printf "\nThere were linting errors, please fix them\n"
  exit 1
fi

exit 0
